### ISSUE TITLE
Review configuration

### ISSUE THREAD

**Issue by ZacharyKlein** [jhipster/generator-jhipster-micronaut#20]
Some Spring-specific configuration appears to remain in the application - review and remove/convert

**Comment by JasonTypesCodes** [comment]
`application-dev.yml` still contains:
```
spring:
  profiles:
    active: dev
    include:
      - swagger
      # Uncomment to activate TLS for the dev profile
      #- tls
  devtools:
    restart:
      enabled: true
      additional-exclude: .h2.server.properties
    livereload:
      enabled: false # we use Webpack dev server + BrowserSync for livereload
  jackson:
    serialization:
      indent-output: true
  mail:
    host: localhost
    port: 25
    username:
    password:
  messages:
    cache-duration: PT1S # 1 second, see the ISO 8601 standard
  thymeleaf:
    cache: false
```
