### ISSUE TITLE
Is it possible to set / as an oauth2 logout path?

### ISSUE THREAD

**Issue by mraible** [jhipster/generator-jhipster-micronaut#224]
##### **Overview of the feature request**

I'm trying to integrate [JHipster + Micronaut support in the Okta CLI](https://github.com/okta/okta-cli/pull/83). One of the issues I've run into is we use `/` as a logout redirect URI for Spring Security. It also works with Quarkus.

If I try the following, it results in a 405 error when I load up `http://localhost:8080`.

```
micronaut:
  security:
    endpoints:
      logout:
        enabled: true
        get-allowed: false
        path: /
```

If I change `...logout.get-allowed` to true, I get an infinite redirect when I load the homepage.

##### **Motivation for or Use Case**

It'd be nice if we could use the same login and logout redirect URIs across JHipster blueprints, so it's easier to configure them for OKta.

##### **Related issues or PR**

https://github.com/okta/okta-cli/pull/83
