### ISSUE TITLE
Unable to log in to a new application with JWT authentication

### ISSUE THREAD

**Issue by mraible** [jhipster/generator-jhipster-micronaut#418]
##### **Overview of the issue**

If I generate an app with the following:

```
mhipster jdl default --skip-jhipster-dependencies
```

I'm unable to log in:

```
i.m.s.t.j.g.JwtTokenGenerator - JOSEException while generating token The secret length must be at least 256 bits
```

##### **Reproduce the error**

```
mhipster jdl default --skip-jhipster-dependencies
docker compose -f src/main/docker/services.yml up
```

Then, try to log in with admin/admin.

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**

<details>
<summary>.yo-rc.json file</summary>
<pre>
{
  "generator-jhipster": {
    "backendType": "micronaut",
    "baseName": "jhipster",
    "blueprints": [
      {
        "name": "generator-jhipster-micronaut",
        "version": "3.4.1"
      }
    ],
    "devServerPort": 4200,
    "entities": [],
    "jhipsterVersion": "8.7.3",
    "languages": [
      "en"
    ],
    "nativeLanguage": "en",
    "prodDatabaseType": "postgresql",
    "serverTestFrameworks": [],
    "skipJhipsterDependencies": true,
    "testFrameworks": [
      []
    ]
  }
}
</pre>
</details>

##### **Environment and Tools**

openjdk version "17.0.13" 2024-10-15
OpenJDK Runtime Environment Temurin-17.0.13+11 (build 17.0.13+11)
OpenJDK 64-Bit Server VM Temurin-17.0.13+11 (build 17.0.13+11, mixed mode, sharing)

git version 2.39.5 (Apple Git-154)

node: v20.18.0
npm: 10.9.0

Docker version 27.3.1, build ce12230

##### **JDL for the Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

<details>
<summary>JDL entity definitions</summary>

<pre>

</pre>
</details>

- [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by mraible** [comment]
@mshima The value for the secret key seems wrong. From `application-dev.yml`:

```yaml
  security:
    token:
      jwt:
        generator:
          access-token:
            expiration: 86400
        signatures:
          secret:
            generator:
              secret: ${jhipster.security.authentication.jwt.base64-secret:}
```
